[font]
size = 10

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[font.normal]
family = "JetBrains Mono"
style = "Regular"

[window]
opacity = 0.9
dynamic_padding = false
decorations = "buttonless"

[window.padding]
x = 10
y = 10

[general]
import = [
    "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
]
